// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iMessengerCoreAPI.Models.Data;

#nullable disable

namespace iMessengerCoreAPI.Models.Migrations
{
    [DbContext(typeof(RGDialogDbContext))]
    partial class RGDialogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("iMessengerCoreAPI.Models.Models.RGDialogsClients", b =>
                {
                    b.Property<Guid>("IDUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateEvent")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IDClient")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDRGDialog")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IDUnique");

                    b.ToTable("RGDialogsClients");
                });
#pragma warning restore 612, 618
        }
    }
}
